CREATE DATABASE entregable_01_radhames_capellan;

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) NOT NULL,
  "email" varchar(30) UNIQUE NOT NULL,
  "password" varchar(20) NOT NULL,
  "age" int NOT NULL,
  "rol_id" int NOT NULL
);

CREATE TABLE "courses_user" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int NOT NULL,
  "course_id" int NOT NULL
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(30) NOT NULL,
  "description" varchar(255) NOT NULL,
  "level_id" int NOT NULL,
  "teacher" varchar(50) NOT NULL,
  "category_id" int NOT NULL,
  "video_id" int NOT NULL
);

CREATE TABLE "courses_video" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(50) NOT NULL,
  "url" varchar(255) UNIQUE NOT NULL
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(30) UNIQUE NOT NULL
);

CREATE TABLE "roles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(25) UNIQUE NOT NULL
);

CREATE TABLE "courses_level" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "level" varchar(25) UNIQUE NOT NULL
);

ALTER TABLE "roles" ADD FOREIGN KEY ("id") REFERENCES "users" ("rol_id");

ALTER TABLE "courses_user" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "courses_user" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("level_id") REFERENCES "courses_level" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id");

ALTER TABLE "courses" ADD FOREIGN KEY ("video_id") REFERENCES "courses_video" ("id");


INSERT INTO roles (name) VALUES ('Student'), ('Teacher'), ('Admin');
SELECT * FROM roles;

INSERT INTO categories (name) VALUES ('DB'), ('Back-End'), ('Front-End'), ('Frameworks'), ('Javascript'), ('Typescript') ;
SELECT * FROM categories;

INSERT INTO courses_level (level) VALUES ('Beginner'), ('Half'), ('Advance');
SELECT * FROM courses_level;

INSERT INTO courses_video (title, url) VALUES ('React for Beginner', 'www.radev.com/reactforbeginners'), ('NodeJs for Advance', 'www.radev.com/node-advance');
SELECT * FROM courses_video;

INSERT INTO users (name, email, password, age, rol_id ) VALUES ('Radhames Capellan', 'radhames@gmail.com', '123098', 34, 3), ('Peter Parker', 'spiderman@gmail.com', '176892', 19, 1), ('Juan Alimaña', 'juanitomaña@gmail.com', '896542', 44, 2);
SELECT * FROM users;

INSERT INTO courses (title, description, level_id, teacher, category_id, video_id ) VALUES ('React for Beginner', 'React Course, proptype, hooks, custom hooks', 1, 'Juan Alimaña', 3, 1), ('NodeJs for Advance', 'NodeJs Course, Express, ORM, Auth', 1, 'Radhames Capellan', 2, 2) ;
SELECT * FROM courses;

